[package]
name = "print-cli-rs"
version = "0.1.0"
edition = "2024"

[target.'cfg(target_os = "linux")'.dependencies]
gtk = { version = "0.11.4", package = "gtk4", features = ["v4_22"] }

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.4"
objc2-app-kit = "0.3.2"
objc2-foundation = "0.3.2"
objc2-pdf-kit = "0.3.2"
